[site]
title = "Nathan Gill"
author = "Nathan Gill <nathan.j.gill@outlook.com>"
description = "Nathan Gill's personal website"
base_url = "https://ngill.net/"
default_template = "page.html"

[build]
include_drafts = false
static_prefix = ""
plugin_dir = "plugins"

[serve]
host = "0.0.0.0"
port = 8080
auto_reload = false

[[plugin]]
name = "rss_generator.py"
hook = "post"
hash = "88961bf763be468339c157aa3bb1bc4182858db7a0aad39165fa5ee75ad7f7ee"
build_dir = "build"
rss_file = "rss.xml"
content_dir = "content"
post_dir = "posts"
title = "Nathan Gill's Blog"
url = "https://ngill.net/"
desc = "Nathan Gill's blog posts on various topics"

[[plugin]]
name = "sitemap_generator.py"
hook = "post"
hash = "84ee882497d41e14f33141754b6e612968654fb67d52cc78f4dcbd4336a9f5d7"
build_dir = "build"
sitemap = "sitemap.xml"
url = "https://ngill.net/"
incl = [ "*.html" ]
excl = [ "404.html" ]

